version: '3'
services:
  app:
    build: .
    image: app:0.0.1
    restart: always
    command: node index.js
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules  # Exclui node_modules do mapeamento